Repository milieuinfo/webcomponent-vl-ui-form-grid, pull requests merged in 2019-09, with the labels that each got.

#29 UIG-218
  vl-form-grid.src.js
Labels: maintenance

#30 Update link naar demo
  vl-form-grid.src.js
Labels: maintenance

#31 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#34 Update dependency vl-ui-textarea to v1.0.9
  package-lock.json
  package.json
Labels: dependencies

#33 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#32 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#23 Update dependency vl-ui-form-message to v2.2.6
  package-lock.json
  package.json
Labels: dependencies

#22 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#21 Update dependency vl-ui-checkbox to v1.0.14
  package-lock.json
  package.json
Labels: dependencies

#20 Update dependency vl-ui-button to v1.1.9
  package-lock.json
Labels: dependencies

#8 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#37 Update dependency vl-ui-button to v1.1.10
  package-lock.json
  package.json
Labels: dependencies

#38 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#40 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#45 Update dependency vl-ui-form-message to v2.2.7
  package-lock.json
  package.json
Labels: dependencies
