Repository milieuinfo/webcomponent-vl-ui-form-grid, pull requests merged in 2020-01, with the labels that each got.

#62 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#63 Update naar laatste util
  package-lock.json
  package.json
Labels: bugfix

#64 Fix src nav aanpassingen in vl-ui-grid
  demo/vl-form-grid.html
  package-lock.json
  package.json
  style.css
  vl-form-grid.src.js
Labels: bugfix

#65 Overbodig NPM release import scripts verwijderd
  package.json
  vl-form-grid.js
Labels: maintenance

#67 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnenDepend op core-branch zonder after
  package.json
Labels: chore

#66 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#68 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#69 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
