Repository milieuinfo/webcomponent-vl-ui-form-grid, pull requests merged in 2020-03, with the labels that each got.

#76 Upate vl-ui-util voor ondersteuning double en single quotes imports
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: bug

#77 Update vl-ui-util
  package-lock.json
  package.json
Labels: chore, maintenance

#78 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#79 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore
